#
# GitLab CI/CD Pipeline for deploying DreamHouse App using Salesforce DX
#
#
# Run these commands before executing any build jobs,
# such as to install dependencies and set environment variables
#
before_script:
    # Install jq, a json parsing library
    - apt update && apt -y install jq
    # Setup SFDX environment variables
    # https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_env_variables.htm
    - export SALESFORCE_CLI_URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    - export SFDX_AUTOUPDATE_DISABLE=false
    - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
    - export SFDX_DOMAIN_RETRY=600
    - export SFDX_LOG_LEVEL=DEBUG
    # Install Salesforce CLI
    - mkdir sfdx
    - wget -qO- $SALESFORCE_CLI_URL | tar xJ -C sfdx --strip-components 1
    - './sfdx/install'
    - export PATH=./sfdx/$(pwd):$PATH
    # Output CLI version and plug-in information
    - sfdx update
    - sfdx --version
    - sfdx plugins --core
    # Authenticate to the Dev Hub from specified Auth URL
    - echo $PLAYGROUND_AUTH_URL > /tmp/sfdx.url
    - sfdx force:auth:sfdxurl:store --sfdxurlfile /tmp/sfdx.url --setalias "DevHub" --setdefaultdevhubusername
#
# Define the stages of our pipeline
#
stages:
    - SO-testing
    - Package-versioning
    - Package-Installation-testing
    - Package-promotion

SO-testing:
    stage: SO-testing
    script:
        # Create scratch org
        - sfdx force:org:create --setdefaultusername --targetdevhubusername DevHub --wait 10 --durationdays 1 --setalias "CodeTestingScratchOrg" edition=developer
        # Push source to Scratch Org
        - sfdx force:source:push --targetusername CodeTestingScratchOrg
        # Run all Apex tests
        - sfdx force:apex:test:run --verbose --codecoverage --resultformat human
        # Delete Scratch Org
        - sfdx force:org:delete --noprompt --targetusername CodeTestingScratchOrg

# The Trailhead provided yml created a new package version within a Scratch Org. We should consider wheather the package should
# be built from the DevHub or a Scratch Org
Package-versioning:
    stage: Package-versioning
    artifacts:
        paths:
            - PACKAGE_VERSION_ID.TXT
    script:
        # Deploy source to DevHub
        - sfdx force:source:deploy --targetusername DevHub --manifest package.xml
        # Increment package version number (taken from the yml file provided through trailhead)
        - echo $PACKAGE_NAME
        - PACKAGE_VERSION_JSON="$(eval sfdx force:package:version:list --concise --released --packages $PACKAGE_NAME --json | jq '.result | sort_by(-.MajorVersion, -.MinorVersion, -.PatchVersion, -.BuildNumber) | .[0] // ""')"
        - echo $PACKAGE_VERSION_JSON
        - IS_RELEASED=$(jq -r '.IsReleased?' <<< $PACKAGE_VERSION_JSON)
        - MAJOR_VERSION=$(jq -r '.MajorVersion?' <<< $PACKAGE_VERSION_JSON)
        - MINOR_VERSION=$(jq -r '.MinorVersion?' <<< $PACKAGE_VERSION_JSON)
        - PATCH_VERSION=$(jq -r '.PatchVersion?' <<< $PACKAGE_VERSION_JSON)
        - BUILD_VERSION="NEXT"
        - if [ -z $MAJOR_VERSION ]; then MAJOR_VERSION=1; fi;
        - if [ -z $MINOR_VERSION ]; then MINOR_VERSION=0; fi;
        - if [ -z $PATCH_VERSION ]; then PATCH_VERSION=0; fi;
        - if [ "$IS_RELEASED" == "true" ]; then MINOR_VERSION=$(($MINOR_VERSION+1)); fi;
        - VERSION_NUMBER="$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.$BUILD_VERSION"
        - echo $VERSION_NUMBER
        # Create packaged version
        - export PACKAGE_VERSION_ID="$(eval sfdx force:package:version:create --package $PACKAGE_NAME --versionnumber $VERSION_NUMBER --installationkeybypass --wait 10 --json | jq -r '.result.SubscriberPackageVersionId')"
        # Save your PACKAGE_VERSION_ID to a file for later use during deploy so you know what version to deploy
        - echo "$PACKAGE_VERSION_ID" > PACKAGE_VERSION_ID.TXT
        - echo $PACKAGE_VERSION_ID
       
Package-Installation-testing:
    stage: Package-Installation-testing
    script:
        # Read the package version id from file created in prior stage
        - export PACKAGE_VERSION_ID=`cat ./PACKAGE_VERSION_ID.TXT`
        - echo $PACKAGE_VERSION_ID
        # Create scratch org
        - sfdx force:org:create --setdefaultusername --targetdevhubusername DevHub --wait 10 --durationdays 1 --setalias "PackageInstallationTestingScratchOrg" edition=developer
        # install package in SO through ID
        - sfdx force:package:install --wait 10 --publishwait 10 --package $PACKAGE_VERSION_ID --noprompt --targetusername PackageInstallationTestingScratchOrg
        # Run all Apex tests
        - sfdx force:apex:test:run --verbose --codecoverage --resultformat human
        # Delete Scratch Org
        - sfdx force:org:delete --noprompt --targetusername PackageInstallationTestingScratchOrg

Package-promotion:
    stage: Package-promotion
    # Will only promote the package if manually run
    when: manual
    script:
        # Read the package version id from file created in prior stage
        - export PACKAGE_VERSION_ID=`cat ./PACKAGE_VERSION_ID.TXT`
        - echo $PACKAGE_VERSION_ID
        # promote package out of beta status
        - sfdx force:package:version:promote --package $PACKAGE_VERSION_ID --targetdevhubusername DevHub