#
# GitLab CI/CD Pipeline for deploying DreamHouse App using Salesforce DX
#
#
# Run these commands before executing any build jobs,
# such as to install dependencies and set environment variables
#
before_script:
    # Decrypt server key
    #- openssl enc -aes-256-cbc -md sha256 -salt -d -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD -pbkdf2
    #
    # Install jq, a json parsing library
    - apt update && apt -y install jq
    # Setup SFDX environment variables
    # https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_env_variables.htm
    - export SALESFORCE_CLI_URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    - export SFDX_AUTOUPDATE_DISABLE=false
    - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
    - export SFDX_DOMAIN_RETRY=600
    - export SFDX_LOG_LEVEL=DEBUG
    # Install Salesforce CLI
    - mkdir sfdx
    - wget -qO- $SALESFORCE_CLI_URL | tar xJ -C sfdx --strip-components 1
    - './sfdx/install'
    - export PATH=./sfdx/$(pwd):$PATH
    # Output CLI version and plug-in information
    - sfdx update
    - sfdx --version
    - sfdx plugins --core
#
# Define the stages of our pipeline
#
stages:
    - SO-creation

SO-creation:
    stage: SO-creation
    script:
        # Authenticate to the Dev Hub from specified Auth URL
        - echo $PLAYGROUND_AUTH_URL > /tmp/sfdx.url
        - sfdx force:auth:sfdxurl:store --sfdxurlfile /tmp/sfdx.url --setalias "PlaygroundDevHub" --setdefaultdevhubusername
        # Create scratch org
        - sfdx force:org:create --setdefaultusername --targetdevhubusername "PlaygroundDevHub" --wait 10 --durationdays 1 --setalias "PackageTestingScratchOrg" edition=developer
        # Install package in ScratchOrg
        - sfdx force:package:install --wait 10 --publishwait 10 --package $TEST_UNMANAGED_PCK_ID --noprompt --targetusername PackageTestingScratchOrg
        # Run all Apex tests
        - sfdx force:apex:test:run --verbose --codecoverage