#
# GitLab CI/CD Pipeline for deploying DreamHouse App using Salesforce DX
#
#
# Run these commands before executing any build jobs,
# such as to install dependencies and set environment variables
#
before_script:
    # Decrypt server key
    #- openssl enc -aes-256-cbc -md sha256 -salt -d -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD -pbkdf2
    #
    # Install jq, a json parsing library
    - apt update && apt -y install jq
    # Setup SFDX environment variables
    # https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_env_variables.htm
    - export SALESFORCE_CLI_URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    - export SFDX_AUTOUPDATE_DISABLE=false
    - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
    - export SFDX_DOMAIN_RETRY=600
    - export SFDX_LOG_LEVEL=DEBUG
    # Install Salesforce CLI
    - mkdir sfdx
    - wget -qO- $SALESFORCE_CLI_URL | tar xJ -C sfdx --strip-components 1
    - './sfdx/install'
    - export PATH=./sfdx/$(pwd):$PATH
    # Output CLI version and plug-in information
    - sfdx update
    - sfdx --version
    - sfdx plugins --core
#
# Define the stages of our pipeline
#
stages:
    - code-testing
#
# Stage 1 -- Create a scratch org for code testing
#
code-testing:
    stage: code-testing
    script:
        # Authenticate to the Dev Hub using the server key
        #- sfdx force:auth:jwt:grant --setdefaultdevhubusername --clientid $SF_CONSUMER_KEY --jwtkeyfile assets/server.key --username $SF_USERNAME
        - authenticate SCRATCHORG $PLAYGROUND_AUTH_URL
        # Create scratch org
        - sfdx force:org:create --setdefaultusername --wait 10 --durationdays 1 edition=developer
        #- sfdx force:org:display
        # Push source to scratch org (this is with source code, all files, etc)
        #- sfdx force:source:push
        # Assign DreamHouse permission set to scratch org default user
        #- sfdx force:user:permset:assign --permsetname DreamHouse
        # Add sample data into app
        #- sfdx force:data:tree:import --plan data/sample-data-plan.json
        # Unit Testing
        #- sfdx force:apex:test:run --wait 10 --resultformat human --codecoverage --testlevel RunLocalTests
        # Delete Scratch Org
        #- sfdx force:org:delete --noprompt


  # Function to authenticate to Salesforce.
  # Don't expose the auth url to the logs.
  # Arguments:
  #     $1 = alias to set
  #     $2 = Sfdx Auth URL
  #     $3 = SFDX AUth URL to use if the previous one isn't set (optional)
  function authenticate() {
    local alias_to_set=$1
    local org_auth_url=$2
    local org_auth_url_backup=$3

    local file=$(mktemp)
    echo $org_auth_url > $file
    local cmd="sfdx force:auth:sfdxurl:store --sfdxurlfile $file --setalias $alias_to_set --json" && (echo $cmd >&2)
    local output=$($cmd)

    sfdx force:config:set defaultusername=$alias_to_set
    sfdx force:config:set defaultdevhubusername=$alias_to_set

    rm $file
  }
