name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Populate auth file with SFDX_URL secret'
        shell: bash
        run: 'echo ${{ secrets.PLAYGROUND_AUTH_URL}} > ./SFDX_URL_STORE.txt'
      - name: 'Authenticate against dev hub'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:auth:sfdxurl:store --sfdxurlfile=./SFDX_URL_STORE.txt --setalias=DevHub --setdefaultdevhubusername'
      - name: 'Create scratch org'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:org:create --setalias=ScratchOrg --setdefaultusername --targetdevhubusername DevHub --durationdays 1 edition=developer'
      - uses: actions/checkout@v2
      - name: 'Push source to ScratchOrg'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:source:push -u ScratchOrg'
      - name: 'Create folder for test results'
        run: mkdir testResults
      - name: 'Run all tests in ScratchOrg'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:apex:test:run --verbose --codecoverage --resultformat human -d ./testResults/'
      - name: 'List testresult files'
        run: |
          cd testResults
          ls
          echo " --- Testresults following KEJ --- "
          cat test-result.txt
          echo " --- Testcodecoverage following KEJ --- "
          cat test-result-codecoverage.json
      #CleanUp, delete ScratchOrg
      - name: 'Delete ScratchOrg'
        uses: forcedotcom/salesforcedx-actions@master
        with:
          args: 'force:org:delete --noprompt --targetusername ScratchOrg'
