name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  #push:
    #branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Salesforce CLI
        run: |
          apt update && apt -y install jq
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      - name: Authenticate DevHub
        run: |
          echo ${{ secrets.PLAYGROUND_AUTH_URL }} > /tmp/sfdx.url
          sfdx force:auth:sfdxurl:store --sfdxurlfile /tmp/sfdx.url --setalias DevHub --setdefaultdevhubusername
      - name: create ScratchOrg
        run: sfdx force:org:create --setdefaultusername --targetdevhubusername DevHub --wait 10 --durationdays 1 --setalias ScratchOrg edition=developer
      - uses: actions/checkout@v2
      - name: 'Push source to ScratchOrg'
        run: sfdx force:source:push --targetusername ScratchOrg
      - name: 'Run all tests in ScratchOrg'
        run: sfdx force:apex:test:run --verbose --codecoverage --resultformat human --targetusername ScratchOrg
      - name: Create new Package Version
        run: sfdx force:package:version:create --package "${{ secrets.PACKAGE_NAME }}" --installationkey "${{ secrets.PACKAGE_INSTALLATION_KEY }}" --targetdevhubusername DevHub --wait 10 --json
      # Update sfdx-project.json and README to use only latest package version
      #- name: 'Update sfdx-project.json and README'
        #id: packaging-updater
        #uses: muenzpraeger/github-action-sfdx-packaging-updater@master
      # Re-add changes back to source
      #- name: 'Add new package version, updated sfdx-project.json and README to source'
        #if: steps.packaging-updater.outputs.isSuccess
        #uses: Automattic/action-commit-to-branch@master
        #with:
            #branch: ${{ github.head_ref }}
            #commit_message: 'Added new package version ID from GitHub workflow'
        #env:
            #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
      #CleanUp, delete ScratchOrg
      - name: 'Delete ScratchOrg'
        run: sfdx force:org:delete --noprompt --targetusername ScratchOrg
