name: Create new package version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  #push:
    #branches: [ master ]
    #paths-ignore:
    #- 'README.md'
    #- 'sfdx-project.json'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- name: Install Salesforce CLI
        #run: |
          #apt update && apt -y install jq
          #wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          #mkdir sfdx-cli
          #tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          #./sfdx-cli/install
      - uses: actions/checkout@master
        with:
          persist-credentials: false 
          fetch-depth: 0 
          path: main
      #- run: cd main
      #- name: Authenticate DevHub
        #run: |
          #echo ${{ secrets.PLAYGROUND_AUTH_URL }} > /tmp/sfdx.url
          #sfdx force:auth:sfdxurl:store --sfdxurlfile /tmp/sfdx.url --setalias DevHub --setdefaultdevhubusername
      #- name: create ScratchOrg
        #run: sfdx force:org:create --setdefaultusername --targetdevhubusername DevHub --wait 10 --durationdays 1 --setalias ScratchOrg edition=developer
      #- name: 'Push source to ScratchOrg'
        #run: sfdx force:source:push --targetusername ScratchOrg
      #- name: 'Run all tests in ScratchOrg'
        #run: sfdx force:apex:test:run --verbose --codecoverage --resultformat human --targetusername ScratchOrg
      #- name: Create new Package Version
        #run: sfdx force:package:version:create --package "${{ secrets.PACKAGE_NAME }}" --installationkey "${{ secrets.PACKAGE_INSTALLATION_KEY }}" --targetdevhubusername DevHub --wait 10 --json
      #- name: 'Run all tests in ScratchOrg'
        #run: sfdx force:apex:test:run --verbose --codecoverage --resultformat human --targetusername ScratchOrg
      
      #TODO update Readme with new IDs to install
      
      #Git push changes
      #- run: |
          #git config --local user.email "action@github.com"
          #git config --local user.name "GitHub Action"
          #git add .
          #git commit -m "generated"
      #- name: Push changes
        #uses: ad-m/github-push-action@master
        #with:
          #github_token: ${{ secrets.GITHUB_TOKEN }} #GitHub Action issued token
          #branch: ${{ github.ref }}
          
      #CleanUp, delete ScratchOrg
      #- name: 'Delete ScratchOrg'
      #  run: sfdx force:org:delete --noprompt --targetusername ScratchOrg
        
      #experimental stuff
      #- name: Install npm ApexDoc CLI
        #run: sudo npm install --global @cparra/apexdocs
        
      #- name: Try generating docu
        #run: apexdocs-generate --sourceDir ./force-app/main/default/classes --targetGenerator docsify
          
      - name: Checkout website repo
        uses: actions/checkout@v2
        with:
          repository: kay-Eigenherd/eghLibWebsite
          persist-credentials: false 
          fetch-depth: 0
          path: website
        
      - run: ls
      - run: cd website/
      - run: ls
      - run: cd /docs
      - run: ls
        
      #- name: rearrange files to easily push #[ -d "/testRepoForSFPackageVersioning" ] && rm -r ./testRepoForSFPackageVersioning || mkdir ./testRepoForSFPackageVersioning
        #run: |
          #mv ./docs/Miscellaneous ./docs/testRepoForSFPackageVersioning
          #cp ./README.md ./docs/testRepoForSFPackageVersioning
          #rm ./docs/README.md
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add docu testRepoForSFPackageVersioning" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.KEJ_TOKEN }}
          branch: 'master'
          repository: 'kay-Eigenherd/eghLibWebsite'
          force: true
